apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: novel-translator-data
  namespace: novel-translator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
